### ISSUE TITLE
Populated C5-C9, C23 when using Super DMG-Jack. Problem or not?

### ISSUE THREAD

**Issue by explit28** [kamicane/Super-DMG-01#6]
Its not an issue, rather an question:

I created the latest Version 1.9 on PCBWay, but the guys populated also C5-C9 and C23.
Can it be ignored when i use Super DMG-Jack, or should i desolder this components?

What will happen when i also populate U4?

Than i will have 2x amplifier: One one the mainboard and one on the jack. Would it be a problem?

Maybe you can give a short explanation here @kamicane 

Thanks a lot!

![IMG_20240604_084833](https://github.com/kamicane/Super-DMG-01/assets/11852348/b2e7a764-71a5-40ce-b9d5-197cba9d108d)

**Comment by kamicane** [comment]
Those extra capacitors should not interfere with the amp on the jack board. You can remove them if you like but it shouldn't be necessary.

If you have the original DMG amp (U4) you can simply install it rather than use the amp on the Super-DMG jack, and do a simple install without the amp. Do not use both.

[Super-DMG Jack full installation (amp on the jack board)](https://github.com/kamicane/Super-DMG-01/tree/main/super-dmg-jack#full-installation)

[Super-DMG Jack simple installation (original DMG amp on the S/DMG board)](https://github.com/kamicane/Super-DMG-01/tree/main/super-dmg-jack#full-installation)

The amp option on the jack board is there mainly to allow building a DMG without harvesting the original amp, it's not really better or worse than the original. It can get very loud on that little speaker tho, if you care for that sort of thing. Headphone output doesn't change as with the Super-DMG the "prosound mod" is automatic.

**Comment by explit28** [comment]
Thank you very much for the clarification, @kamicane !

i will leave the capacitors and use the amp in the super-DMG Jack, because its already fully populated.
